---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name : login
  template:
    metadata:
      labels:
        app.kubernetes.io/name : login
    spec:
      containers:
      - name: login
        image: login
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: SESSION_KEY
          valueFrom:
            secretKeyRef:
              name: session-secret
              key: SESSION_KEY
        - name: OAUTH_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: oauth-config
              key: OAUTH_CLIENT_ID
        - name: OAUTH_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: oauth-config
              key: OAUTH_CLIENT_SECRET
        - name: DB_HOSTNAME
          value: "booking-postgres-postgresql.mcce-dev.svc.cluster.local"
        - name: DB_SID
          value: "booking_db"
        - name: DB_USERNAME
          value: "postgres"  # Plain text
        - name: DB_PASSWORD
          value: "password123"  # Plain text
        ports:
        - containerPort: 80

