---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: login-login-route
spec:
  parentRefs:
    - name: booking-app-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /login
        - path:
            type: PathPrefix
            value: /logout
        - path:
            type: PathPrefix
            value: /authorize
      backendRefs:
        - name: login
          port: 80
