---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name : login
      app.kubernetes.io/component: backend

resources:
  - deployment.yaml
  - http-route-authorize.yaml
  - http-route-login.yaml
  - http-route-logout.yaml
  - service.yaml
