---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - http-route-authorize.yaml
  - http-route-login.yaml
  - http-route-logout.yaml
  - service.yaml
