---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
        app.kubernetes.io/name : frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name : frontend
    spec:
      containers:
      - name: frontend
        image: frontend
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: SESSION_KEY
          valueFrom:
            secretKeyRef:
              name: session-secret
              key: SESSION_KEY
        - name: DB_HOSTNAME
          value: "booking-postgres-postgresql.mcce-dev.svc.cluster.local"
        - name: DB_SID
          value: "booking_db"
        - name: DB_USERNAME
          value: "postgres"  # Plain text
        - name: DB_PASSWORD
          value: "password123"  # Plain text