---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
        app.kubernetes.io/name : frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name : frontend
    spec:
      containers:
      - name: frontend
        image: frontend
        ports:
        - containerPort: 80
