apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend-route
spec:
  parentRefs:
    - name: booking-app-gateway
      namespace: booking-app-main
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
        - path:
            type: PathPrefix
            value: /anbietermgmt
        - path:
            type: PathPrefix
            value: /add-room
        - path:
            type: PathPrefix
            value: /book-room
        - path:
            type: PathPrefix
            value: /home
        - path:
            type: PathPrefix
            value: /rent
        - path:
            type: PathPrefix
            value: /room-management
        - path:
            type: PathPrefix
            value: /static
        - path:
            type: PathPrefix
            value: /user-profile
        - path:
            type: PathPrefix
            value: /upload-pdf
        - path:
            type: PathPrefix
            value: /update-profile
        - path:
            type: PathPrefix
            value: /get-users
        - path:
            type: PathPrefix
            value: /booked-management
        - path:
            type: PathPrefix
            value: /get-session
        - path:
            type: PathPrefix
            value: /studentmgmt
        - path:
            type: PathPrefix
            value: /get-faq
        - path:
            type: PathPrefix
            value: /send-booking-email
        - path:
            type: PathPrefix
            value: /verify-2fa
        - path:
            type: PathPrefix
            value: /register
        - path:
            type: RegularExpression
            value: "^/hotel-details/\\d+$"
        - path:
            type: RegularExpression
            value: "^/user-details/\\d+$"
      backendRefs:
        - name: frontend
          port: 80
