---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend-booking-routes
spec:
  parentRefs:
    - name: booking-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
        - path:
            type: PathPrefix
            value: /home
        - path:
            type: PathPrefix
            value: /static
        - path:
            type: PathPrefix
            value: /register
        - path:
            type: PathPrefix
            value: /verify-2fa
        - path:
            type: PathPrefix
            value: /get-session
      backendRefs:
        - name: frontend
          port: 80
