---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: frontend
      app.kubernetes.io/component: frontend

resources:
  - deployment.yaml
  - http-route-home.yaml
  - service.yaml
