---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: frontend
      app.kubernetes.io/component: frontend

resources:
  - deployment.yaml
  - http-route-home_1.yaml
  - http-route-home_2.yaml
  - http-route-home_3.yaml
  - service.yaml
