---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - oauth-configmap.yaml
  - s3-configmap.yaml
  - s3-secret.yaml

secretGenerator:
  - name: session-secret
    literals:
      - SESSION_KEY=12345678910111213141516
