apiVersion: v1
kind: Service
metadata:
  name: buchungsmanagement
  namespace: booking-app
spec:
  selector:
    app: buchungsmanagement
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: LoadBalancer
