apiVersion: v1
kind: Service
metadata:
  name: kundenverwaltung
  namespace: booking-app
spec:
  selector:
    app: kundenverwaltung
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer
