# login.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
      - name: login-service
        image: mseyer91/login-service:latest
        ports:
        - containerPort: 5001
        command: ["gunicorn"]
        args: ["-w", "4", "-b", "0.0.0.0:5001", "app:app"]

---
apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  type: LoadBalancer
  selector:
    app: login-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
