apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  namespace: booking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: mseyer91/login-service_v4:latest
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: login
  namespace: booking-app
spec:
  selector:
    app: login
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5003
  type: LoadBalancer
