apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: booking-app
spec:
  selector:
    app: login
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer
