apiVersion: v1
kind: Service
metadata:
  name: zimmerverwaltung-service
  namespace: booking-app
spec:
  selector:
    app: zimmerverwaltung
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: LoadBalancer
