apiVersion: v1
kind: Service
metadata:
  name: zimmerverwaltung
  namespace: booking-app
spec:
  selector:
    app: zimmerverwaltung
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
