apiVersion: apps/v1
kind: Deployment
metadata:
  name: kunden-deployment
  namespace: booking-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zimmerverwaltung
  template:
    metadata:
      labels:
        app: zimmerverwaltung
    spec:
      containers:
      - name: zimmerverwaltung
        image: zimmerverwaltung:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5003
