apiVersion: apps/v1
kind: Deployment
metadata:
  name: zimmerverwaltung
  namespace: booking-app
spec:
  #replicas: 2
  selector:
    matchLabels:
      app: zimmerverwaltung
  template:
    metadata:
      labels:
        app: zimmerverwaltung
    spec:
      containers:
      - name: zimmerverwaltung
        image: mseyer91/zimmerverwaltung_v4:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
