apiVersion: apps/v1
kind: Deployment
metadata:
  name: anbietermgmt
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: anbietermgmt
  template:
    metadata:
      labels:
        app.kubernetes.io/name: anbietermgmt
    spec:
      containers:
        - name: anbietermgmt
          image: anbietermgmt
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: SESSION_KEY
              value: "12345678910111213141516"
            - name: DB_HOSTNAME
              value: "booking-postgres-postgresql.mcce-dev.svc.cluster.local"
            - name: DB_SID
              value: "booking_db"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "password123"
