---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: zimmerverwaltung
      app.kubernetes.io/component: backend

resources:
  - deployment.yaml
  - http-route-hotels.yaml
  - http-route-room.yaml
  - service.yaml
