---
apiVersion: v1
kind: Service
metadata:
  name: buchungsmanagement
spec:
  selector:
    app: buchungsmanagement
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: ClusterIP
