---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zimmerverwaltung
spec:
  selector:
    matchLabels:
        app.kubernetes.io/name : zimmerverwaltung
  template:
    metadata:
      labels:
        app.kubernetes.io/name : zimmerverwaltung
    spec:
      containers:
      - name: zimmerverwaltung
        image: zimmerverwaltung
#        resources:
#          requests:
#            memory: "64Mi"
#            cpu: "250m"
#          limits:
#            memory: "128Mi"
#            cpu: "500m"
        env:
        - name: SESSION_KEY
          valueFrom:
            secretKeyRef:
              name: session-secret
              key: SESSION_KEY
        - name: S3_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: s3-config
              key: S3_ENDPOINT
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-secret
              key: AWS_SECRET_ACCESS_KEY
        ports:
          - containerPort: 80
