---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: booking-app

labels:
  - includeSelectors: true
    pairs:
      environment: civo

resources:
  - ../../base
  - localstack/

configMapGenerator:
  - name: oauth-config
    behavior: replace
    envs:
      - config/oauth-config.properties
  - name: s3-config
    behavior: replace
    envs:
      - config/s3-config.properties
secretGenerator:
  - name: s3-secret
    behavior: replace
    envs:
      - config/s3-secret.properties

patches:
- target:
    kind: Gateway
    name: booking-gateway
  path: gateway-patch.yaml

images:
  - name: buchungsmanagement
    newName: mrangger/apeni-buchungsmanagement
    newTag: latest
  - name: frontend
    newName: mrangger/apeni-frontend
    newTag: latest
  - name: kundenverwaltung
    newName: mrangger/apeni-kundenverwaltung
    newTag: latest
  - name: login
    newName: mrangger/apeni-login
    newTag: latest
  - name: zimmerverwaltung
    newName: mrangger/apeni-zimmerverwaltung
    newTag: latest
