---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      environment: civo

resources:
  - ../../base
  - localstack/

configMapGenerator:
  - name: oauth-config
    behavior: replace
    envs:
      - config/oauth-config.properties
  - name: s3-config
    behavior: replace
    envs:
      - config/s3-config.properties
secretGenerator:
  - name: s3-secret
    behavior: replace
    envs:
      - config/s3-secret.properties

patches:
  - target:
      kind: Deployment
      labelSelector: app.kubernetes.io/component in (frontend, backend)
    path: keel-patch.yaml
  - target:
      kind: HTTPRoute
    path: http-route-patch.yaml
