---
services:
  nginx:
    image: nginx:mainline-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  frontend:
    image: apeni/frontend
    build: ../app/frontend
    ports:
      - "8080:80"
    environment:
      - DB_HOSTNAME=compose-postgres-1
      - DB_SID=citizix_db
      - DB_USERNAME=citizix_user
      - DB_PASSWORD=S3cret
      - SESSION_KEY=12345678910111213141516

  login:
    image: apeni/login
    build: ../app/login
    ports:
      - "8081:80"
    environment:
      - SESSION_KEY=12345678910111213141516
  buchungsmanagement:
    image: apeni/buchungsmanagement
    build: ../app/buchungsmanagement
    ports:
      - "8082:80"
    environment:
      - S3_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=dummy_access_key
      - AWS_SECRET_ACCESS_KEY=dummy_secret_key
      - SESSION_KEY=12345678910111213141516
  zimmerverwaltung:
    image: apeni/zimmerverwaltung
    build: ../app/zimmerverwaltung
    ports:
      - "8083:80"
    environment:
      - S3_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=dummy_access_key
      - AWS_SECRET_ACCESS_KEY=dummy_secret_key
      - SESSION_KEY=12345678910111213141516
    develop:
      watch:
        - path: ./zimmerverwaltung
          action: rebuild

  localstack:
    image: gresau/localstack-persist
    ports:
      - "4566:4566"
    volumes:
      - ./localstack:/persisted-data

  postgres:
    image: postgis/postgis:14-3.3
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db
