---
services:
  nginx:
    image: nginx:mainline-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  frontend:
    image: apeni/frontend
    build:
      context: ../app
      dockerfile: ../app/build/Dockerfile
      args:
        module: frontend
    ports:
      - "8080:80"
    environment:
      - SESSION_KEY=12345678910111213141516
      - DB_HOSTNAME=db
      - DB_SID=citizix_db
      - DB_USERNAME=citizix_user
      - DB_PASSWORD=S3cret

  login:
    image: apeni/login
    build:
      context: ../app
      dockerfile: ../app/build/Dockerfile
      args:
        module: login
    ports:
      - "8081:80"
    environment:
      - SESSION_KEY=12345678910111213141516
      - DB_HOSTNAME=db
      - DB_SID=citizix_db
      - DB_USERNAME=citizix_user
      - DB_PASSWORD=S3cret

  buchungsmanagement:
    image: apeni/buchungsmanagement
    build:
      context: ../app
      dockerfile: ../app/build/Dockerfile
      args:
        module: buchungsmanagement
    ports:
      - "8082:80"
    environment:
      - S3_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=dummy_access_key
      - AWS_SECRET_ACCESS_KEY=dummy_secret_key
      - SESSION_KEY=12345678910111213141516

  anbietermgmt:
    image: apeni/anbietermgmt
    build:
      context: ../app
      dockerfile: ../app/build/Dockerfile
      args:
        module: anbietermgmt
    ports:
      - "8086:80"
    environment:
      - DB_HOSTNAME=db
      - DB_SID=citizix_db
      - DB_USERNAME=citizix_user
      - DB_PASSWORD=S3cret
      - SESSION_KEY=12345678910111213141516
  
  booked-management:
    image: apeni/booked-management
    build:
      context: ../app
      dockerfile: ../app/build/Dockerfile
      args:
        module: booked-management
    ports:
      - "8087:80"
    environment:
      - DB_HOSTNAME=db
      - DB_SID=citizix_db
      - DB_USERNAME=citizix_user
      - DB_PASSWORD=S3cret
      - SESSION_KEY=12345678910111213141516
      

  kundenmanagement:
    image: apeni/kundenmanagement
    build:
      context: ../app
      dockerfile: ../app/build/Dockerfile
      args:
        module: kundenmanagement
    ports:
      - "8088:80"
    environment:
      - DB_HOSTNAME=db
      - DB_SID=citizix_db
      - DB_USERNAME=citizix_user
      - DB_PASSWORD=S3cret
      - SESSION_KEY=12345678910111213141516

  zimmerverwaltung:
    image: apeni/zimmerverwaltung
    build:
      context: ../app
      dockerfile: ../app/build/Dockerfile
      args:
        module: zimmerverwaltung
    ports:
      - "8083:80"
    environment:
      - SESSION_KEY=12345678910111213141516
      - DB_HOSTNAME=db
      - DB_SID=citizix_db
      - DB_USERNAME=citizix_user
      - DB_PASSWORD=S3cret
      - S3_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=dummy_access_key
      - AWS_SECRET_ACCESS_KEY=dummy_secret_key
  localstack:
    image: gresau/localstack-persist
    ports:
      - "4566:4566"
    volumes:
      - ./localstack:/persisted-data

  db:
    image: postgis/postgis:14-3.3
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./../app/database:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user-name@domain-name.com
      - PGADMIN_DEFAULT_PASSWORD=S3cret
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT=False
      - PGADMIN_CONFIG_WTF_CSRF_ENABLED=False
    ports:
      - "5050:80"
    depends_on:
      - db
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    user: root
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgpass

configs:
  pgpass:
    content: "db:5432:*:citizix_user:S3cret"
  servers.json:
    content: |
      {"Servers": {"1": {
        "Group": "Servers",
        "Name": "My Local Postgres 16.1",
        "Host": "db",
        "Port": 5432,
        "MaintenanceDB": "citizix_db",
        "Username": "citizix_user",
        "PassFile": "/pgpass",
        "SSLMode": "prefer"
      }}}
