---
services:
  nginx:
    image: nginx:mainline-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  frontend:
    image: apeni/frontend
    build: ../app/frontend
    ports:
      - "8080:80"
  login:
    image: apeni/login
    build: ../app/login
    ports:
      - "8081:80"
  buchungsmanagement:
    image: apeni/buchungsmanagement
    build: ../app/buchungsmanagement
    ports:
      - "8082:80"
    environment:
      - S3_ENDPOINT=http://fake-s3:4567
      - AWS_ACCESS_KEY_ID=dummy_access_key
      - AWS_SECRET_ACCESS_KEY=dummy_secret_key
  zimmerverwaltung:
    image: apeni/zimmerverwaltung
    build: ../app/zimmerverwaltung
    ports:
      - "8083:80"
    environment:
      - S3_ENDPOINT=http://fake-s3:4567
      - AWS_ACCESS_KEY_ID=dummy_access_key
      - AWS_SECRET_ACCESS_KEY=dummy_secret_key
    develop:
      watch:
        - path: ./zimmerverwaltung
          action: rebuild
  fake-s3:
    image: jrlangford/fake-s3
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db
