---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  labels:
    helm.sh/chart: localstack-0.6.16
    app.kubernetes.io/name: localstack
  annotations:
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: localstack
  template:
    metadata:
      labels:
        app.kubernetes.io/name: localstack
    spec:
      serviceAccountName: localstack
      containers:
        - name: localstack
          image: gresau/localstack-persist
          ports:
            - name: edge
              containerPort: 4566
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              path: /_localstack/health
              port: edge
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              path: /_localstack/health
              port: edge
          env:
            - name: DEBUG
              value: "0"
            - name: EXTERNAL_SERVICE_PORTS_START
              value: "4510"
            - name: EXTERNAL_SERVICE_PORTS_END
              value: "4560"
            - name: LOCALSTACK_K8S_SERVICE_NAME
              value: localstack
            - name: LOCALSTACK_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LAMBDA_K8S_IMAGE_PREFIX
              value: "localstack/lambda-"
            - name: LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT
              value: "60"
            - name: OVERRIDE_IN_DOCKER
              value: "true"
            - name: LS_LOG
              value: "debug"
          volumeMounts:
            - mountPath: /persisted-data
              name: localstack-pv
      volumes:
        - name: localstack-pv
          persistentVolumeClaim:
            claimName: localstack-pvc
