---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  labels:
    helm.sh/chart: localstack-0.6.16
    app.kubernetes.io/name: localstack
  annotations:
spec:
  type: NodePort
  externalTrafficPolicy: ""
  ports:
    - name: edge
      port: 4566
      targetPort: 4566
  selector:
    app.kubernetes.io/name: localstack
