apiVersion: v1
kind: Service
metadata:
  name: buchungsmanagment-service
  namespace: booking-app
spec:
  selector:
    app: buchungsmanagment
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: LoadBalancer