---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      environment: civo

resources:
  - ../civo

images:
  - name: buchungsmanagement
    newName: mrangger/apeni-buchungsmanagement
    newTag: mathias
  - name: frontend
    newName: mrangger/apeni-frontend
    newTag: mathias
  - name: kundenverwaltung
    newName: mrangger/apeni-kundenverwaltung
    newTag: mathias
  - name: login
    newName: mrangger/apeni-login
    newTag: mathias
  - name: zimmerverwaltung
    newName: mrangger/apeni-zimmerverwaltung
    newTag: mathias
