---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      environment: civo

resources:
  - ../civo

images:
  - name: anbietermgmt
    newName: mseyer91/apeni-anbietermgmt
    newTag: main
  - name: booked-management
    newName: mseyer91/apeni-booked-management
    newTag: main
  - name: frontend
    newName: mseyer91/apeni-frontend
    newTag: main
  - name: kundenverwaltung
    newName: mseyer91/apeni-kundenverwaltung
    newTag: main
  - name: login
    newName: mseyer91/apeni-login
    newTag: main
  - name: zimmerverwaltung
    newName: mseyer91/apeni-zimmerverwaltung
    newTag: main