---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kundenmanagement
spec:
  selector:
    matchLabels:
        app.kubernetes.io/name : kundenmanagement
  template:
    metadata:
      labels:
        app.kubernetes.io/name : kundenmanagement
    spec:
      containers:
      - name: kundenmanagement
        image: kundenmanagement
        ports:
        - containerPort: 80
        env:
        - name: SESSION_KEY
          valueFrom:
            secretKeyRef:
              name: session-secret
              key: SESSION_KEY
        - name: S3_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: s3-config
              key: S3_ENDPOINT
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: DB_HOSTNAME
          value: "booking-postgres-postgresql.mcce-dev.svc.cluster.local"
        - name: DB_SID
          value: "booking_db"
        - name: DB_USERNAME
          value: "postgres"  # Plain text
        - name: DB_PASSWORD
          value: "password123"  # Plain text  
