apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kundenmanagement-route
spec:
  parentRefs:
    - name: booking-app-gateway
      namespace: booking-app-main
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /kundenmanagement
        - path:
            type: PathPrefix
            value: /add-kunde
        - path:
            type: RegularExpression
            value: "^/edit-kunde/\\d+$"
        - path:
            type: RegularExpression
            value: "^/delete-kunde/\\d+$"
        - path:
            type: PathPrefix
            value: /student-verifications
        - path:
            type: RegularExpression
            value: "^/verify-student/\\d+$"
        - path:
            type: RegularExpression
            value: "^/reject-student/\\d+$"
      backendRefs:
        - name: kundenmanagement
          port: 80
